//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeUnit.RTD {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RTD.IRealTimeDriver")]
    public interface IRealTimeDriver {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriver/SendRandomValue", ReplyAction="http://tempuri.org/IRealTimeDriver/SendRandomValueResponse")]
        void SendRandomValue(string uid, int random);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriver/SendRandomValue", ReplyAction="http://tempuri.org/IRealTimeDriver/SendRandomValueResponse")]
        System.Threading.Tasks.Task SendRandomValueAsync(string uid, int random);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriver/ConnectRtu", ReplyAction="http://tempuri.org/IRealTimeDriver/ConnectRtuResponse")]
        bool ConnectRtu(string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriver/ConnectRtu", ReplyAction="http://tempuri.org/IRealTimeDriver/ConnectRtuResponse")]
        System.Threading.Tasks.Task<bool> ConnectRtuAsync(string uid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRealTimeDriverChannel : RealTimeUnit.RTD.IRealTimeDriver, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RealTimeDriverClient : System.ServiceModel.ClientBase<RealTimeUnit.RTD.IRealTimeDriver>, RealTimeUnit.RTD.IRealTimeDriver {
        
        public RealTimeDriverClient() {
        }
        
        public RealTimeDriverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RealTimeDriverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeDriverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeDriverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendRandomValue(string uid, int random) {
            base.Channel.SendRandomValue(uid, random);
        }
        
        public System.Threading.Tasks.Task SendRandomValueAsync(string uid, int random) {
            return base.Channel.SendRandomValueAsync(uid, random);
        }
        
        public bool ConnectRtu(string uid) {
            return base.Channel.ConnectRtu(uid);
        }
        
        public System.Threading.Tasks.Task<bool> ConnectRtuAsync(string uid) {
            return base.Channel.ConnectRtuAsync(uid);
        }
    }
}
