//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeUnit.RTDServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RTDServiceReference.IRealTimeDriver")]
    public interface IRealTimeDriver {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriver/SendRandomValue", ReplyAction="http://tempuri.org/IRealTimeDriver/SendRandomValueResponse")]
        System.ValueTuple<bool, int> SendRandomValue(string address, int random, byte[] message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriver/SendRandomValue", ReplyAction="http://tempuri.org/IRealTimeDriver/SendRandomValueResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, int>> SendRandomValueAsync(string address, int random, byte[] message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriver/ConnectRtu", ReplyAction="http://tempuri.org/IRealTimeDriver/ConnectRtuResponse")]
        bool ConnectRtu(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriver/ConnectRtu", ReplyAction="http://tempuri.org/IRealTimeDriver/ConnectRtuResponse")]
        System.Threading.Tasks.Task<bool> ConnectRtuAsync(string address);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRealTimeDriverChannel : RealTimeUnit.RTDServiceReference.IRealTimeDriver, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RealTimeDriverClient : System.ServiceModel.ClientBase<RealTimeUnit.RTDServiceReference.IRealTimeDriver>, RealTimeUnit.RTDServiceReference.IRealTimeDriver {
        
        public RealTimeDriverClient() {
        }
        
        public RealTimeDriverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RealTimeDriverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeDriverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeDriverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ValueTuple<bool, int> SendRandomValue(string address, int random, byte[] message) {
            return base.Channel.SendRandomValue(address, random, message);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, int>> SendRandomValueAsync(string address, int random, byte[] message) {
            return base.Channel.SendRandomValueAsync(address, random, message);
        }
        
        public bool ConnectRtu(string address) {
            return base.Channel.ConnectRtu(address);
        }
        
        public System.Threading.Tasks.Task<bool> ConnectRtuAsync(string address) {
            return base.Channel.ConnectRtuAsync(address);
        }
    }
}
